# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 Sönke Pinkernelle

"""Build CSS custom-property artefacts from the canonical theme JSON.

PortfoliFLOW keeps its design tokens — colours, fonts, chart palettes,
spacing — in ``config/ui_theme*.json`` and ``config/chart_theme.json``.
``gui/theme.py`` consumes those JSON files at runtime via
``core/ui_theme.py`` (no pre-generated Qt-side artefact is produced or
needed; QSS is composed at startup from the live token dict). The web
variant cannot do that — browsers do not parse Python — so this script
projects the same tokens onto the only contract a stylesheet can read:
CSS custom properties on ``:root`` and per-variant scopes
(``:root[data-theme="light"]``, ``:root[data-theme="corporate_blue"]``).

The script enforces a single rule: **the JSON sources are the only
source of truth, and the generated CSS file is committed alongside its
sources so drift is caught at code review rather than at runtime.** A
pre-commit hook regenerates the artefact on every change to the
relevant JSON files.

Output behaviour:

* Emits ``web/static/css/theme.css``. The PyQt6 stylesheet is composed
  at runtime from the same JSON sources by ``gui/theme.py`` —
  inspecting that module shows it consumes the live theme dict via
  ``core.ui_theme.get_ui_theme()`` and the only persisted artefact
  needed is therefore the web CSS. Per ADR-0037 §7's "binding
  constraint is that both worlds derive from the same JSON source",
  the contract is satisfied: the web side reads the generated
  ``theme.css``; the Qt side reads the same JSON directly.
* Idempotent: identical inputs produce byte-identical output. No
  timestamps, no environment-dependent paths, sorted variant order.
* Invocable as a module (``python -m scripts.generate_theme_artifacts``)
  and as a callable from a pre-commit hook
  (``scripts.generate_theme_artifacts:main``).

Usage::

    python -m scripts.generate_theme_artifacts
    python -m scripts.generate_theme_artifacts --check  # CI / pre-commit
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any
from collections.abc import Mapping

logger = logging.getLogger(__name__)

_REPO_ROOT: Path = Path(__file__).resolve().parents[1]
_DEFAULT_CONFIG_DIR: Path = _REPO_ROOT / "config"
_DEFAULT_OUTPUT: Path = _REPO_ROOT / "web" / "static" / "css" / "theme.css"

_UI_THEME_PATTERN = "ui_theme*.json"
_DEFAULT_UI_THEME = "ui_theme.json"
_CHART_THEME_FILENAME = "chart_theme.json"

# Variants whose values are mirrored as scoped overrides on ``:root``.
# Mapping of source filename → ``data-theme`` attribute value.
_VARIANT_FILENAME_TO_NAME: dict[str, str] = {
    "ui_theme_light.json": "light",
    "ui_theme_corporate_blue.json": "corporate_blue",
}

_HEADER = (
    "/*\n"
    " * PortfoliFLOW design tokens — generated by\n"
    " * scripts/generate_theme_artifacts.py from\n"
    " * config/ui_theme*.json and config/chart_theme.json.\n"
    " *\n"
    " * DO NOT EDIT BY HAND. Re-run the script (or commit the JSON\n"
    " * change with the pre-commit hook installed) to regenerate.\n"
    " */\n"
)

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(name: str) -> str:
    """Normalise a token name into a CSS-custom-property fragment.

    Args:
        name: Raw key from the JSON source.

    Returns:
        A lowercase, hyphen-separated slug suitable for embedding in
        ``--<prefix>-<slug>``. Underscores, spaces, and punctuation
        collapse to a single hyphen; leading/trailing hyphens are
        trimmed.
    """
    cleaned = _SLUG_RE.sub("-", name.lower()).strip("-")
    return cleaned


def _emit_pairs(prefix: str, value: Any) -> list[tuple[str, str]]:
    """Flatten a nested JSON value into a list of CSS-property pairs.

    Numeric scalars become unitless strings; strings pass through
    verbatim; arrays are joined with ``", "`` (matches CSS
    comma-separated value syntax for font-family lists and colour
    palettes); booleans become ``"true"`` / ``"false"``. Nested dicts
    recurse with the prefix extended by the slugified key.

    Args:
        prefix: The CSS variable prefix accumulated so far
            (e.g. ``"--background"``).
        value: The current node from the JSON tree.

    Returns:
        Ordered list of ``(custom-property, value)`` pairs. The order
        matches the JSON's natural traversal — deterministic given the
        ``json.load`` ordering, which preserves source order in
        Python 3.7+.
    """
    pairs: list[tuple[str, str]] = []
    if isinstance(value, Mapping):
        for key, child in value.items():
            if str(key).startswith("_"):
                # Skip metadata fields like ``_comment``, ``_version``,
                # ``_display_name`` — they're for human readers, not
                # token consumers.
                continue
            slug = _slug(str(key))
            child_prefix = f"{prefix}-{slug}" if slug else prefix
            pairs.extend(_emit_pairs(child_prefix, child))
        return pairs

    if isinstance(value, list):
        # Render the whole list as one comma-separated value, AND emit
        # per-index variants for palette-style consumers that want to
        # read individual entries.
        joined = ", ".join(_render_scalar(item) for item in value)
        pairs.append((prefix, joined))
        for idx, item in enumerate(value):
            pairs.append((f"{prefix}-{idx}", _render_scalar(item)))
        return pairs

    pairs.append((prefix, _render_scalar(value)))
    return pairs


def _render_scalar(value: Any) -> str:
    """Render a JSON scalar into a CSS-safe string.

    Args:
        value: A leaf JSON value.

    Returns:
        Stringified form: integers and floats unitless, booleans
        lowercased, strings as-is.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return f"{value}"
    return str(value)


def _format_block(selector: str, pairs: list[tuple[str, str]]) -> str:
    """Render a CSS rule block.

    Args:
        selector: The CSS selector (``:root`` or
            ``:root[data-theme="..."]``).
        pairs: List of ``(custom-property, value)`` pairs.

    Returns:
        A formatted CSS block ending in a single newline.
    """
    lines = [f"{selector} {{"]
    for prop, val in pairs:
        lines.append(f"    {prop}: {val};")
    lines.append("}\n")
    return "\n".join(lines)


def _load_json(path: Path) -> dict[str, Any]:
    """Read a JSON file from disk.

    Args:
        path: Absolute path to the JSON file.

    Returns:
        The parsed dictionary.

    Raises:
        FileNotFoundError: If the file does not exist.
        json.JSONDecodeError: If the file contains malformed JSON.
    """
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object at {path}, got {type(data).__name__}.")
    return data


def _split_pf_section(theme: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any] | None]:
    """Pull a top-level ``pf`` section out of a theme payload.

    The ``pf`` namespace holds shell-level tokens (sidebar widths,
    status-bar height, background levels, accent overlays) that the
    web shell consumes under the ``--pf-*`` prefix. It can appear in
    either ``ui_theme*.json`` or ``chart_theme.json`` and is emitted
    independently of the file's natural prefix.

    Args:
        theme: Parsed contents of a theme JSON file.

    Returns:
        A pair ``(rest, pf)`` where ``rest`` is the theme without the
        ``pf`` key and ``pf`` is the sub-payload (or ``None`` when the
        section is absent).
    """
    pf = theme.get("pf")
    rest = {k: v for k, v in theme.items() if k != "pf"}
    if isinstance(pf, Mapping):
        return rest, dict(pf)
    return rest, None


def _build_pairs_for_ui_theme(theme: dict[str, Any]) -> list[tuple[str, str]]:
    """Project an ``ui_theme*.json`` payload to ``--ui-*`` properties.

    A top-level ``pf`` section is split out and emitted as ``--pf-*``
    tokens (see :func:`_split_pf_section`).

    Args:
        theme: Parsed contents of one ``ui_theme*.json`` file.

    Returns:
        List of ``(--ui-<...>, value)`` pairs followed by any
        ``(--pf-<...>, value)`` pairs in JSON-source order.
    """
    rest, pf = _split_pf_section(theme)
    pairs = _emit_pairs("--ui", rest)
    if pf is not None:
        pairs.extend(_emit_pairs("--pf", pf))
    return pairs


def _build_pairs_for_chart_theme(theme: dict[str, Any]) -> list[tuple[str, str]]:
    """Project ``chart_theme.json`` to ``--chart-*`` properties.

    A top-level ``pf`` section is split out and emitted as ``--pf-*``
    tokens (see :func:`_split_pf_section`).

    Args:
        theme: Parsed contents of ``chart_theme.json``.

    Returns:
        List of ``(--chart-<...>, value)`` pairs followed by any
        ``(--pf-<...>, value)`` pairs in JSON-source order.
    """
    rest, pf = _split_pf_section(theme)
    pairs = _emit_pairs("--chart", rest)
    if pf is not None:
        pairs.extend(_emit_pairs("--pf", pf))
    return pairs


def render_css(config_dir: Path) -> str:
    """Render the full ``theme.css`` content for the given config dir.

    Args:
        config_dir: Directory containing the theme JSON files.

    Returns:
        The complete CSS document, deterministic given the input JSON
        files.

    Raises:
        FileNotFoundError: If the default UI theme JSON is missing.
    """
    default_ui_path = config_dir / _DEFAULT_UI_THEME
    if not default_ui_path.exists():
        raise FileNotFoundError(
            f"Default UI theme not found at {default_ui_path}; the script cannot proceed."
        )

    default_ui = _load_json(default_ui_path)
    ui_pairs = _build_pairs_for_ui_theme(default_ui)

    chart_path = config_dir / _CHART_THEME_FILENAME
    if chart_path.exists():
        chart_pairs = _build_pairs_for_chart_theme(_load_json(chart_path))
    else:
        chart_pairs = []
        logger.warning("chart_theme.json not found at %s; skipping.", chart_path)

    parts: list[str] = [_HEADER]
    parts.append(_format_block(":root", ui_pairs + chart_pairs))

    # Variants — render in a stable, alphabetised order so the output
    # is byte-deterministic regardless of filesystem traversal order.
    variant_files = sorted(
        path
        for path in config_dir.glob(_UI_THEME_PATTERN)
        if path.name in _VARIANT_FILENAME_TO_NAME
    )
    for variant_path in variant_files:
        variant_name = _VARIANT_FILENAME_TO_NAME[variant_path.name]
        variant_payload = _load_json(variant_path)
        variant_pairs = _build_pairs_for_ui_theme(variant_payload)
        parts.append("\n")
        parts.append(_format_block(f':root[data-theme="{variant_name}"]', variant_pairs))

    return "".join(parts)


def _write_if_changed(target: Path, content: str) -> bool:
    """Write ``content`` to ``target`` only if the bytes differ.

    Args:
        target: Output file path.
        content: Generated CSS content.

    Returns:
        ``True`` when the file was written, ``False`` when the existing
        contents already matched.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    new_bytes = content.encode("utf-8")
    if target.exists() and target.read_bytes() == new_bytes:
        return False
    target.write_bytes(new_bytes)
    return True


def main(argv: list[str] | None = None) -> int:
    """Entry point for module invocation and pre-commit hooks.

    Args:
        argv: Optional CLI argument list (used by tests). When ``None``,
            ``sys.argv[1:]`` is used.

    Returns:
        ``0`` on success or no-change-in-check-mode; ``1`` when
        ``--check`` is specified and the on-disk artefact is stale.
    """
    parser = argparse.ArgumentParser(
        prog="generate_theme_artifacts",
        description=(
            "Generate web/static/css/theme.css from the canonical "
            "config/ui_theme*.json and config/chart_theme.json sources."
        ),
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=_DEFAULT_CONFIG_DIR,
        help="Directory containing the theme JSON files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help="Path of the generated CSS file.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write; exit non-zero if the on-disk artefact is "
            "stale. Suitable for CI / pre-commit verification."
        ),
    )
    args = parser.parse_args(argv)

    content = render_css(args.config_dir)

    if args.check:
        if not args.output.exists():
            sys.stderr.write(
                f"theme.css missing at {args.output}; run "
                "`python -m scripts.generate_theme_artifacts`.\n"
            )
            return 1
        if args.output.read_bytes() != content.encode("utf-8"):
            sys.stderr.write(
                f"theme.css at {args.output} is stale; run "
                "`python -m scripts.generate_theme_artifacts`.\n"
            )
            return 1
        return 0

    changed = _write_if_changed(args.output, content)
    if changed:
        sys.stdout.write(f"wrote {args.output}\n")
    else:
        sys.stdout.write(f"unchanged {args.output}\n")
    return 0


if __name__ == "__main__":  # pragma: no cover - module entry shim
    raise SystemExit(main())
